### ISSUE TITLE
Hostname error

### ISSUE THREAD

**Issue by Xcyth** [kurusukono/pvea#9]
this thing will just not accept the hosname as ip:port, anyone have any idea on how to do anything about it?

**Comment by kurusukono** [comment]
Just to make sure, you're doing "hostname:port" and not anything such as "https://hostname:port"?

Are you using port 8006?

**Comment by simonfrfr** [comment]
@Xcyth You are correct, currently pvea does not accept hostname as IP:PORT, created a pull request to enabled this functionality. All you will have to do from now is provide hostname in some valid form: https://IP:PORT, IP:PORT, FQDN:PORT, FQDN, https://FQDN, etc. And pvea should be able to take in your request. If you do not specify a port, it will default to the default port 8006.

**Comment by Xcyth** [comment]
> @Xcyth You are correct, currently pvea does not accept hostname as IP:PORT, created a pull request to enabled this functionality. All you will have to do from now is provide hostname in some valid form: https://IP:PORT, IP:PORT, FQDN:PORT, FQDN, https://FQDN, etc. And pvea should be able to take in your request. If you do not specify a port, it will default to the default port 8006.

ah alright

**Comment by simonfrfr** [comment]
(Just have to wait for the Patch to get merged)

**Comment by kurusukono** [comment]
Thank you all,

Esp. you simon. I have been *very* busy in my life and have not had the time to do any web development. I am now getting free time again and I look forward to working on pvea again.

**Comment by kurusukono** [comment]
merged.
